### ISSUE TITLE
FEATURE: Make gene box expandable, increase default height to 25 genes

### ISSUE THREAD

**Issue by Munfred** [WormBase/wormcells-viz#15]
The same way that the genes and cells text box can be enlarged vertically (see screenshot), could we to the same for the selected gene list?  At the moment it only shows about 10 genes with might be too few, a default height for 25 genes i think might be good
![image](https://user-images.githubusercontent.com/12504176/119400190-a84e1700-bc8e-11eb-933c-746ff3bf8e47.png)

**Comment by valearna** [comment]
I made the select larger, but it's not expandable
