### ISSUE TITLE
EDUARDO: Write description overview for landing page explaining each visualization

### ISSUE THREAD

**Issue by Munfred** [WormBase/wormcells-viz#18]
Write description overview for landing page explaining each visualization

**Comment by valearna** [comment]
Taken from WB call notes: On the landing page (once I write the explanation doc) make it clear that WormBase reprocesses the data from scratch and so there may be differences with published tools for the same dataset

**Comment by valearna** [comment]
Also from WB call notes: add colab notebooks in documentation
