### ISSUE TITLE
Add option to select cell types in histograms

### ISSUE THREAD

**Issue by valearna** [WormBase/wormcells-viz#49]
Similar to the Heatmap panel (Cell subtypes search bar option), in the Gene Expression histogram panel of Wormcells-viz, an option to select specific cell subtypes will be useful.

**Comment by Munfred** [comment]
New menu looks good, but I noticed on the histograms that the "deselect all" button doesnt seem to be working:
http://cervino.caltech.edu:3000/ridge_line/WBGene00000149

**Comment by valearna** [comment]
I've added a 'refresh' button to avoid fetching data every time a cell is checked or unchecked. This also fixes the 'deselect all' button issue.

**Comment by Munfred** [comment]
refresh button is awesome
