### ISSUE TITLE
Implement option to sort histogram by average expression level

### ISSUE THREAD

**Issue by valearna** [WormBase/wormcells-viz#54]
Use the data for the heatmap if the user asks to sort by expression frequency: slice heatmap matrix by gene, sort by expression, use cell types order

**Comment by Munfred** [comment]
Was this deployed at http://cervino.caltech.edu:3000/ridge_line/default

Not a huge deal if not

**Comment by valearna** [comment]
Not Yet @Munfred, I'm working on it right now

**Comment by valearna** [comment]
Ready to be tested on cervino

**Comment by Munfred** [comment]
looks awesome. thanks!
