### ISSUE TITLE
Add message that a gene is not present in data when user searches for it

### ISSUE THREAD

**Issue by valearna** [WormBase/wormcells-viz#57]
Some genes are not possible to select (for example hnd-1 in the bendavid dataset) – perhaps these are not expressed in the particular dataset but would still be good to have them show up in the list in a wormbase specific implementation of the tool.

**Comment by Munfred** [comment]
I searched for hnd-1 and it didn't come up, did you change anything? i used http://cervino.caltech.edu:3000/heatmap

**Comment by valearna** [comment]
@Munfred I've restricted all cell and gene searches to the entities that are present in the dataset. I've added a short description to say that genes not in the dataset won't show up. Let me know if this is enough clear

**Comment by Munfred** [comment]
Is that explanation on the deploy at http://cervino.caltech.edu:3000/heatmap? I didn't see it

But yeah that is good enough

**Comment by valearna** [comment]
Yes, when you click "search genes" the text appears as placeholder in the search box: "only entities included in the dataset are shown"

**Comment by Munfred** [comment]
Ahh I see now I had put text too quickly.

Great!
