### ISSUE TITLE
Add readme to repo with deploy instructions

### ISSUE THREAD

**Issue by Munfred** [WormBase/wormcells-viz#9]

**Comment by valearna** [comment]
I'll add a description on how to deploy the API and the frontend so that @Munfred can try to deply the app on other datasets (e.g., the UCLA one)

**Comment by valearna** [comment]
Added a simple readme file. Let me know when you have time to take a look at it / try the deployment

**Comment by valearna** [comment]
Update the README file with new api arguments

**Comment by Munfred** [comment]
everything works great
